### ISSUE TITLE
> Task :react-native-device-info:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by icecapp** [react-native-device-info/react-native-device-info#1350]
| Version  | "react-native-device-info": "^8.4.5" | 
| Affected OS | Android |
| OS Version  | 12 |

## Current behavior

Hi, just updated my `/android/build.gradle` file

```java
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
```

and started getting 

```
> Task :react-native-device-info:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings
213 actionable tasks: 17 executed, 196 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: /Users/icecapp/Documents/projects/rn/napp/node_modules/@notifee/react-native/android/src/main/java/io/invertase/notifee/NotifeeReactUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/icecapp/Documents/projects/rn/napp/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/icecapp/Documents/projects/rn/napp/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
An exception has occurred in the compiler (1.8.0_242). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.code.TypeAnnotations.annotationType(TypeAnnotations.java:231)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:294)
```
...
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

    at makeError (/Users/icecapp/Documents/projects/rn/napp/node_modules/execa/index.js:174:9)
    at /Users/icecapp/Documents/projects/rn/napp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/icecapp/Documents/projects/rn/napp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/icecapp/Documents/projects/rn/napp/node_modules/@react-native-community/cli/build/index.js:192:9)
```

Apologies in advance if this issue is not related to `react-native-device-info`

Any ideas?

**Comment by icecapp** [comment]
I'm actually getting this after installation `react-native-bootsplash` which asks for 
```
buildscript {
  ext {
    buildToolsVersion = "30.0.2"
    minSdkVersion = 23 // <- AndroidX splashscreen has basic support for 21 (only the background color), so 23 is best
    compileSdkVersion = 31 // <- set at least 31
    targetSdkVersion = 31 // <- set at least 31
```

**Comment by siniarski** [comment]
Started showing up after updating compileSdkVersion and targetSdkVersion to 31.

I fixed it by upgrading my selected Gradle JDK from 1.8 -> 11 (Preferences -> Build, Execution, Deployment -> Build Tools -> Gradle -> Gradle JDK)

**Comment by mikehardy** [comment]
Yep 31 api requires jdk11

**Comment by icecapp** [comment]
Alright so I `init`ed a fresh new project, added few libs before `react-native-device-info` and I'm still getting the same error as original post

package.json
```js
  "dependencies": {
    "@sentry/react-native": "^3.2.3",
    "promise": "^8.0.3",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-bootsplash": "^4.0.1",
    "react-native-contacts": "^7.0.2",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-device-info": "^8.4.8",
    "react-native-flipper": "^0.121.1"
  },
```

```js
> npx react-native info   
info Fetching system and libraries information...
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 27.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.asdf/installs/nodejs/16.2.0/bin/node
    Yarn: 1.22.10 - ~/.asdf/shims/yarn
    npm: 7.13.0 - ~/.asdf/installs/nodejs/16.2.0/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

and then in Android Studio: 
![Screen Shot 2021-11-25 at 12 24 43 PM](https://user-images.githubusercontent.com/85805465/143482457-c149ec94-f888-4d25-8529-4b03c5d57745.png)

**Comment by mikehardy** [comment]
If you are still getting the same error, then you are using JDK1.8. The error *literally contains 1.8* in the error.

> 
> An exception has occurred in the compiler (1.8.0_242). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your > program and the following diagnostic in your report. Thank you.

**Comment by mikehardy** [comment]
I can't be more clear on this one: It's a JDK8 issue. You must use JDK11. Something is wrong in your local environment unfortunately. I won't have time to correspond more.

**Comment by WenLonG12345** [comment]
> Alright so I `init`ed a fresh new project, manually updated everything to jdk11, added few libs before `react-native-device-info` and I'm still getting the same error as original post
> 
> package.json
> 
> ```js
>   "dependencies": {
>     "@sentry/react-native": "^3.2.3",
>     "promise": "^8.0.3",
>     "react": "17.0.2",
>     "react-native": "0.66.3",
>     "react-native-bootsplash": "^4.0.1",
>     "react-native-contacts": "^7.0.2",
>     "react-native-country-picker-modal": "^2.0.0",
>     "react-native-device-info": "^8.4.8",
>     "react-native-flipper": "^0.121.1"
>   },
> ```
> 
> ```js
> > npx react-native info   
> info Fetching system and libraries information...
> System:
>     OS: macOS 12.0.1
>     CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
>     Memory: 27.88 MB / 16.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 16.2.0 - ~/.asdf/installs/nodejs/16.2.0/bin/node
>     Yarn: 1.22.10 - ~/.asdf/shims/yarn
>     npm: 7.13.0 - ~/.asdf/installs/nodejs/16.2.0/bin/npm
>     Watchman: 2021.11.15.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.2 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
>     Android SDK:
>       API Levels: 29, 30, 31
>       Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
>       System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 2020.3 AI-203.7717.56.2031.7784292
>     Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
>   Languages:
>     Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2 
>     react-native: 0.66.3 => 0.66.3 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> and then in Android Studio: ![Screen Shot 2021-11-25 at 12 24 43 PM](https://user-images.githubusercontent.com/85805465/143482457-c149ec94-f888-4d25-8529-4b03c5d57745.png)
> 
> android/build.gradle
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "30.0.2"
>         minSdkVersion = 23
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>         ndkVersion = "21.4.7075529"
>     }
> ```

I am getting the same issue. And I now just remove this dependecy and the app is successfully build. 
I am not sure whether it is JDK8 issue, but switching to JDK11 not solving the problem.

**Comment by mikehardy** [comment]
Switching to JDK11, **if done correctly** will solve the problem.
This is definitely not a module bug.
Carefully examine whether JDK11 is actually in use in the build, versus just that you think it is in use. I've already worked with a few people who thought they were using JDK11 but in fact they were not because of some obscure setting or a different way of executing gradle.

The compiler bug in play is intermittent. If this module doesn't trigger it, some other module will eventually.

**Comment by icecapp** [comment]
Maybe there could be some indication in the docs about where to upgrade it exactly, for this lib and `react-native-bootsplash` (that I know @mikehardy is also involved in) which explicitly requires jdk11

I still haven't figured it out since creating this issue. Asked on SO, reactiflux, slack... no dice. Currently working with a few libs commented out pending resolution of this issue.

**Comment by mikehardy** [comment]
After that, running `yarn react-native run-android` or `cd android && ./gradlew installDebug` should work, as they use your system `$PATH`. How people have the Android Studio configured I've no idea, but that's on stack overflow https://stackoverflow.com/a/67414820/9910298

**Comment by tsejerome** [comment]
> > Alright so I `init`ed a fresh new project, manually updated everything to jdk11, added few libs before `react-native-device-info` and I'm still getting the same error as original post
> > package.json
> > ```js
> >   "dependencies": {
> >     "@sentry/react-native": "^3.2.3",
> >     "promise": "^8.0.3",
> >     "react": "17.0.2",
> >     "react-native": "0.66.3",
> >     "react-native-bootsplash": "^4.0.1",
> >     "react-native-contacts": "^7.0.2",
> >     "react-native-country-picker-modal": "^2.0.0",
> >     "react-native-device-info": "^8.4.8",
> >     "react-native-flipper": "^0.121.1"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > > npx react-native info   
> > info Fetching system and libraries information...
> > System:
> >     OS: macOS 12.0.1
> >     CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
> >     Memory: 27.88 MB / 16.00 GB
> >     Shell: 5.8 - /bin/zsh
> >   Binaries:
> >     Node: 16.2.0 - ~/.asdf/installs/nodejs/16.2.0/bin/node
> >     Yarn: 1.22.10 - ~/.asdf/shims/yarn
> >     npm: 7.13.0 - ~/.asdf/installs/nodejs/16.2.0/bin/npm
> >     Watchman: 2021.11.15.00 - /usr/local/bin/watchman
> >   Managers:
> >     CocoaPods: 1.11.2 - /usr/local/bin/pod
> >   SDKs:
> >     iOS SDK:
> >       Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
> >     Android SDK:
> >       API Levels: 29, 30, 31
> >       Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
> >       System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
> >       Android NDK: Not Found
> >   IDEs:
> >     Android Studio: 2020.3 AI-203.7717.56.2031.7784292
> >     Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
> >   Languages:
> >     Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
> >   npmPackages:
> >     @react-native-community/cli: Not Found
> >     react: 17.0.2 => 17.0.2 
> >     react-native: 0.66.3 => 0.66.3 
> >     react-native-macos: Not Found
> >   npmGlobalPackages:
> >     *react-native*: Not Found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then in Android Studio: ![Screen Shot 2021-11-25 at 12 24 43 PM](https://user-images.githubusercontent.com/85805465/143482457-c149ec94-f888-4d25-8529-4b03c5d57745.png)
> > android/build.gradle
> > ```
> > buildscript {
> >     ext {
> >         buildToolsVersion = "30.0.2"
> >         minSdkVersion = 23
> >         compileSdkVersion = 31
> >         targetSdkVersion = 31
> >         ndkVersion = "21.4.7075529"
> >     }
> > ```
> 
> I am getting the same issue. And I now just remove this dependecy and the app is successfully build. I am not sure whether it is JDK8 issue, but switching to JDK11 not solving the problem.

For whoever not being able to find the location
File --> Structure --> SDK Location --> JDK Location was moved to Gradle Settings --> Tada~

**Comment by imkrishh** [comment]
Updating the JDK to the one recommended in RN docs solved the issue for me.

`brew tap homebrew/cask-versions`
`brew install --cask zulu11`

https://reactnative.dev/docs/environment-setup#installing-dependencies

**Comment by smali-kazmi** [comment]
> Updating the JDK to the one recommended in RN docs solved the issue for me.
> 
> `brew tap homebrew/cask-versions` `brew install --cask zulu11`
> 
> https://reactnative.dev/docs/environment-setup#installing-dependencies

it fixed by issue

**Comment by arun1989** [comment]
If anyone get example same issue please update your JDK 1.8 to JDK 11 and it will work.

**Comment by vladanyes** [comment]
> Switching to JDK11, **if done correctly** will solve the problem. This is definitely not a module bug. Carefully examine whether JDK11 is actually in use in the build, versus just that you think it is in use. I've already worked with a few people who thought they were using JDK11 but in fact they were not because of some obscure setting or a different way of executing gradle.
> 
> The compiler bug in play is intermittent. If this module doesn't trigger it, some other module will eventually.

turned out I had `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0)` in my `.bash_profile`. After I replaced it with another version the issue went away. Thanks @mikehardy

**Comment by pjcape** [comment]
For Anybody Still looking for solutions in 2024 try this out,
Add org.gradle.java.home=path of your jdk like this: 
![image](https://github.com/react-native-device-info/react-native-device-info/assets/61577815/e35b7f50-5cb5-4a20-819b-8e9389438213)

It specifies the Java home directory that Gradle should use when executing Java-related tasks, such as compiling Java code or running Java applications.

stackoverflow:
https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version
